security:
  password:
    strength: 10
  token:
    max-age-seconds: 86400
    secret: bkr5aI5AAtS5kbwN
server:
  port: 8002
  context-path: /uaa
spring:
  application:
    name: uaa-service
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka/
  instance:
    statusPageUrlPath: ${server.context-path}/info
    healthCheckUrlPath: ${server.context-path}/health
management:
  context-path: /

