version: '3.1'

services:
  uaa-database:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=p4SSW0rd
      - MYSQL_DATABASE=uaa
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=dbp4ss
  uaa-service:
    image: g00glen00b/uaa-service:latest
    depends_on:
      - uaa-database
    ports:
      - 8002:8002
    environment:
      - DATABASE_HOST=uaa-database
      - DATABASE_USER=dbuser
      - DATABASE_PASSWORD=dbp4ss
      - DATABASE_NAME=uaa
      - DATABASE_PORT=3306
      - CONFIG_HOST=config-service
      - CONFIG_PORT=8000
      - SERVER_PORT=8002
      - SECURITY_TOKEN_SECRET=bkr5aI5AAtS5kbwN
      - SECURITY_PASSWORD_STRENGTH=10
      - SECURITY_TOKEN_MAX_AGE_SECONDS=604800
      - DISCOVERY_HOST=discovery-service
      - DISCOVERY_PORT=8001
      - SPRING_PROFILES_ACTIVE=container,container-db,container-stream
      - ZOOKEEPER_HOST=kafka
      - ZOOKEEPER_PORT=2181
      - KAFKA_HOST=kafka
      - KAFKA_PORT=9092
      - JAVA_OPTIONS=-XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -XX:MaxRAMFraction=1
  registration-database:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=p4SSW0rd
      - MYSQL_DATABASE=registration
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=dbp4ss
  registration-service:
    image: g00glen00b/registration-service:latest
    depends_on:
      - registration-database
    ports:
      - 8006:8006
    environment:
      - DATABASE_HOST=registration-database
      - DATABASE_USER=dbuser
      - DATABASE_PASSWORD=dbp4ss
      - DATABASE_NAME=registration
      - DATABASE_PORT=3306
      - CONFIG_HOST=config-service
      - CONFIG_PORT=8000
      - SERVER_PORT=8007
      - DISCOVERY_HOST=discovery-service
      - DISCOVERY_PORT=8001
      - SPRING_PROFILES_ACTIVE=container,container-db,container-stream
      - MAIL_CONFIGURATION=/run/secrets/mail-configuration
      - ZOOKEEPER_HOST=kafka
      - ZOOKEEPER_PORT=2181
      - KAFKA_HOST=kafka
      - KAFKA_PORT=9092
      - JAVA_OPTIONS=-XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -XX:MaxRAMFraction=1
    secrets:
      - mail-configuration
  profile-database:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=p4SSW0rd
      - MYSQL_DATABASE=profiles
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=dbp4ss
  profile-service:
    image: g00glen00b/profile-service:latest
    depends_on:
      - profile-database
    ports:
      - 8004:8004
    environment:
      - DATABASE_HOST=profile-database
      - DATABASE_USER=dbuser
      - DATABASE_PASSWORD=dbp4ss
      - DATABASE_NAME=profiles
      - DATABASE_PORT=3306
      - CONFIG_HOST=config-service
      - CONFIG_PORT=8000
      - SERVER_PORT=8004
      - DISCOVERY_HOST=discovery-service
      - DISCOVERY_PORT=8001
      - ZOOKEEPER_HOST=kafka
      - ZOOKEEPER_PORT=2181
      - KAFKA_HOST=kafka
      - KAFKA_PORT=9092
      - SPRING_PROFILES_ACTIVE=container,container-db,container-stream
      - JAVA_OPTIONS=-XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -XX:MaxRAMFraction=1
  blog-database:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=p4SSW0rd
      - MYSQL_DATABASE=articles
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=dbp4ss
  blog-service:
    image: g00glen00b/blog-service:latest
    depends_on:
      - blog-database
    ports:
      - 8003:8003
    environment:
      - DATABASE_HOST=blog-database
      - DATABASE_USER=dbuser
      - DATABASE_PASSWORD=dbp4ss
      - DATABASE_NAME=articles
      - DATABASE_PORT=3306
      - CONFIG_HOST=config-service
      - CONFIG_PORT=8000
      - SERVER_PORT=8003
      - DISCOVERY_HOST=discovery-service
      - DISCOVERY_PORT=8001
      - SPRING_PROFILES_ACTIVE=container,container-db
      - JAVA_OPTIONS=-XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -XX:MaxRAMFraction=1
  config-service:
    image: g00glen00b/config-service:latest
    ports:
      - 8000:8000
    environment:
      - SERVER_PORT=8000
      - SPRING_CLOUD_CONFIG_SERVER_GIT_URI=https://github.com/g00glen00b/microservice-demo-config.git # Lazy fix for SSH issues in container
      - SPRING_PROFILES_ACTIVE=container
      - JAVA_OPTIONS=-XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -XX:MaxRAMFraction=1
  discovery-service:
    image: g00glen00b/discovery-service:latest
    ports:
      - 8001:8001
    environment:
      - SERVER_PORT=8001
      - CONFIG_HOST=config-service
      - CONFIG_PORT=8000
      - SPRING_PROFILES_ACTIVE=container
      - JAVA_OPTIONS=-XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -XX:MaxRAMFraction=1
  gateway-service:
    image: g00glen00b/gateway-service:latest
    ports:
      - 8005:8005
    environment:
      - SERVER_PORT=8005
      - CONFIG_HOST=config-service
      - CONFIG_PORT=8000
      - DISCOVERY_HOST=discovery-service
      - DISCOVERY_PORT=8001
      - SPRING_PROFILES_ACTIVE=container
      - JAVA_OPTIONS=-XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -XX:MaxRAMFraction=1
  admin-dashboard:
    image: g00glen00b/admin-dashboard:latest
    ports:
      - 8007:8007
    environment:
      - SERVER_PORT=8007
      - CONFIG_HOST=config-service
      - CONFIG_PORT=8000
      - DISCOVERY_HOST=discovery-service
      - DISCOVERY_PORT=8001
      - SPRING_PROFILES_ACTIVE=container
      - JAVA_OPTIONS=-XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -XX:MaxRAMFraction=1
  kafka:
    image: spotify/kafka
    ports:
      - 2181:2181
      - 9092:9092
      - 7209:7209
    environment:
      JMX_PORT: 7209
      ADVERTISED_HOST: localhost
      ADVERTISED_PORT: 9092
secrets:
   mail-configuration:
     file: mail-configuration.properties